PROD:
  hathor_nodes: node.explorer.hathor.network,node1.mainnet.hathor.network,node2.mainnet.hathor.network
  redis_key_prefix: hathor-explorer-service

DEV:
  api_url: http://localhost:3001/
  lambda_invoke_url: http://localhost:3002/
  data_aggregator_lambda_name: hathor-explorer-service-dev-network_data_aggregator
  hathor_core_domain: node1.foxtrot.testnet.hathor.network 
  hathor_nodes: node1.foxtrot.testnet.hathor.network
  redis_key_prefix: hathor-explorer-service-dev
  redis_host: localhost
  redis_port: 6379
  redis_db: 0
