FROM nikolaik/python-nodejs:python3.8-nodejs16

WORKDIR /app

RUN apt-get update && apt-get install -y wget

# copy the dependencies file to the working directory
COPY package-lock.json package.json /app/

RUN npm install

COPY poetry.lock pyproject.toml /app/

# Install dependencies
RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi 

COPY . /app

# Run the service
EXPOSE 3001
EXPOSE 3002
EXPOSE 4569
CMD [ "npm", "start" ]
