# set base image (host OS)
FROM python:3.9-slim

# set the working directory in the container
WORKDIR /app

# install poetry
RUN pip install poetry

# copy the dependencies file to the working directory
COPY poetry.lock pyproject.toml /app/

# install dependencies
RUN poetry config virtualenvs.create false \
  && poetry install --without dev --no-interaction --no-ansi

# copy the content of the local src directory to the working directory
COPY . .
# command to run on container start
CMD [ "python", "-u", "./daemons_runner.py" ]
