version: "3.9"
services:
  daemons:
    build:
      context: .
      dockerfile: Dockerfile_Daemons 
    stdin_open: true
    network_mode: host
    env_file:
      - .env.example
  redis:
    image: "redis:6-alpine"
    ports: 
      - 6379:6379
  explorer-service:
    build:
      context: .
      dockerfile: Dockerfile_Service
    ports: 
      - 3001:3001
    env_file:
      - .env.example