# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: hathor-explorer-service
useDotenv: true
# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: python3.8
  region: ${env:AWS_DEFAULT_REGION}
  lambdaHashingVersion: 20201221
  vpc:
    securityGroupIds:
      - ${env:AWS_VPC_DEFAULT_SG_ID}
    subnetIds:
      - ${env:AWS_SUBNET_ID_1}
      - ${env:AWS_SUBNET_ID_2}
      - ${env:AWS_SUBNET_ID_3}
  environment:
    HATHOR_CORE_DOMAIN: ${env:HATHOR_CORE_DOMAIN}
    HATHOR_NODES: ${env:HATHOR_NODES}
    REDIS_KEY_PREFIX: ${env:REDIS_KEY_PREFIX}
    REDIS_HOST: ${env:REDIS_HOST}
    REDIS_PORT: ${env:REDIS_PORT}
    REDIS_DB: ${env:REDIS_DB}
    METADATA_BUCKET: ${env:METADATA_BUCKET}
    CORS_ALLOWED_ORIGIN: ${env:CORS_ALLOWED_ORIGIN}
    NODE_CACHE_TTL: ${env:NODE_CACHE_TTL}

plugins:
  - serverless-s3-local
  - serverless-offline
  - serverless-python-requirements
  - serverless-api-gateway-caching

package:
  individually: true
  patterns:
    - '!*'
    - '!**/*'
    - 'common/**'
    - 'domain/**'
    - 'gateways/**'
    - 'usecases/**'
    - 'utils/**'
    - '!**/__pycache__'

custom:
  serverless-offline:
    httpPort: ${env:API_PORT}
  pythonRequirements:
    layer: true
  s3:
    host: localhost
    directory: /tmp
  apiGatewayCaching:
    enabled: true
    ttlInSeconds: 300

functions:
  get_node_handler:
    handler: handlers/get_node_handler.handle
    package:
      patterns:
        - 'handlers/get_node_handler.py'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: node/{hash}
          method: get
          cors: true
          request:
            parameters:
              paths:
                hash: true

  list_nodes_handler:
    handler: handlers/list_nodes_handler.handle
    package:
      patterns:
        - 'handlers/list_nodes_handler.py'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: node/
          method: get
          cors: true

  get_network_handler:
    handler: handlers/get_network_handler.handle
    package:
      patterns:
        - 'handlers/get_network_handler.py'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: network/
          method: get
          cors: true

  node_data_aggregator_handler:
    handler: handlers/node_data_aggregator.handle
    package:
      patterns:
        - 'handlers/node_data_aggregator.py'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }

  get_token_handler:
    handler: handlers/get_token_handler.handle
    package:
      patterns:
        - 'handlers/get_token_handler.py'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: token/{hash}
          method: get
          cors: true
          request:
            parameters:
              paths:
                hash: true
          caching:
            enabled: true
            ttlInSeconds: 15
            cacheKeyParameters:
              - name: request.path.hash

  get_dag_metadata_handler:
    handler: handlers/get_dag_metadata_handler.handle
    package:
      patterns:
        - 'handlers/get_dag_metadata_handler.py'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: metadata/dag
          method: get
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 10
            cacheKeyParameters:
              - name: request.querystring.id

  node_api_get_address_balance:
    handler: handlers/node_api.get_address_balance
    timeout: 15
    maximumRetryAttempts: 0
    package:
      patterns:
        - 'handlers/node_api.py'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: node_api/address_balance
          method: get
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 300
            cacheKeyParameters:
              - name: request.querystring.address

  node_api_get_address_search:
    handler: handlers/node_api.get_address_search
    timeout: 15
    maximumRetryAttempts: 0
    package:
      patterns:
        - 'handlers/node_api.py'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: node_api/address_search
          method: get
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 300
            cacheKeyParameters:
              - name: request.querystring.address
              - name: request.querystring.count
              - name: request.querystring.token
              - name: request.querystring.page
              - name: request.querystring.hash

  node_api_get_version:
    handler: handlers/node_api.get_version
    maximumRetryAttempts: 0
    package:
      patterns:
        - 'handlers/node_api.py'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: node_api/version
          method: get
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 3600

  node_api_get_dashboard_tx:
    handler: handlers/node_api.get_dashboard_tx
    maximumRetryAttempts: 0
    package:
      patterns:
        - 'handlers/node_api.py'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: node_api/dashboard_tx
          method: get
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 10
            cacheKeyParameters:
              - name: request.querystring.block
              - name: request.querystring.tx

  node_api_get_tx_acc_w:
    handler: handlers/node_api.get_transaction_acc_weight
    maximumRetryAttempts: 0
    package:
      patterns:
        - 'handlers/node_api.py'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: node_api/transaction_acc_weight
          method: get
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 5
            cacheKeyParameters:
              - name: request.querystring.id

  node_api_get_token_history:
    handler: handlers/node_api.get_token_history
    maximumRetryAttempts: 0
    package:
      patterns:
        - 'handlers/node_api.py'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: node_api/token_history
          method: get
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 10
            cacheKeyParameters:
              - name: request.querystring.id
              - name: request.querystring.count
              - name: request.querystring.hash
              - name: request.querystring.page
              - name: request.querystring.timestamp

  node_api_get_transaction:
    handler: handlers/node_api.get_transaction
    maximumRetryAttempts: 0
    package:
      patterns:
        - 'handlers/node_api.py'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: node_api/transaction
          method: get
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 10
            cacheKeyParameters:
              - name: request.querystring.id

  node_api_list_transactions:
    handler: handlers/node_api.list_transactions
    maximumRetryAttempts: 0
    package:
      patterns:
        - 'handlers/node_api.py'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: node_api/transactions
          method: get
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 10
            cacheKeyParameters:
              - name: request.querystring.type
              - name: request.querystring.count
              - name: request.querystring.hash
              - name: request.querystring.page
              - name: request.querystring.timestamp

  node_api_get_token:
    handler: handlers/node_api.get_token
    maximumRetryAttempts: 0
    package:
      patterns:
        - 'handlers/node_api.py'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: node_api/token
          method: get
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 10
            cacheKeyParameters:
              - name: request.querystring.id

  node_api_list_tokens:
    handler: handlers/node_api.list_tokens
    maximumRetryAttempts: 0
    package:
      patterns:
        - 'handlers/node_api.py'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: node_api/tokens
          method: get
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 3600

  node_api_decode_tx:
    handler: handlers/node_api.decode_tx
    maximumRetryAttempts: 0
    package:
      patterns:
        - 'handlers/node_api.py'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: node_api/decode_tx
          method: get
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 300
            cacheKeyParameters:
              - name: request.querystring.hex_tx

  node_api_push_tx:
    handler: handlers/node_api.push_tx
    maximumRetryAttempts: 0
    package:
      patterns:
        - 'handlers/node_api.py'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: node_api/push_tx
          method: get
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 5
            cacheKeyParameters:
              - name: request.querystring.hex_tx

  node_api_gviz_dot_neighbors:
    handler: handlers/node_api.graphviz_dot_neighbors
    maximumRetryAttempts: 0
    package:
      patterns:
        - 'handlers/node_api.py'
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: node_api/graphviz/neighbours.dot
          method: get
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 10
            cacheKeyParameters:
              - name: request.querystring.tx
              - name: request.querystring.graph_type
              - name: request.querystring.max_level
