name: "Install Python and Dependencies"
description: "Install Python and Dependencies"

inputs:
  python_version:
    description: "Python version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install poetry
      shell: bash
      run: |
        pip -q --no-input install poetry poetry-plugin-export
    - name: Set up Python
      # https://github.com/actions/setup-python/releases/tag/v6.2.0
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
      with:
        python-version: ${{ inputs.python_version }}
        cache: 'poetry'

    - name: Install Python Dependencies
      shell: bash
      run: |
        poetry install

    - name: Linters
      shell: bash
      run: |
        poetry run make check