openapi: 3.0.0
info:
  version: "0.0.1"
  title: "Explorer Service"
  license:
    name: MIT
servers:
  - url: "http://0.0.0.0:3001/dev/"
  - url: "https://explorer-service.hathor.network/"
paths:
  /wallet/address/tokens:
    $ref: "./openapi/wallet_service.yml#/methods/address_tokens"
  /wallet/address/balance:
    $ref: "./openapi/wallet_service.yml#/methods/address_balance"
  /wallet/address/history:
    $ref: "./openapi/wallet_service.yml#/methods/address_history"
