name: PR Validation
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches: [master, dev]
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - name: Checkout to branch
        # https://github.com/actions/checkout/releases/tag/v3.5.3
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Set up Python and Dependencies
        uses: ./.github/workflows/lib/setup-python
        with:
          python_version: ${{ matrix.python-version }}
      - name: Run Tests
        run: |
          poetry run make test
        env:
          AWS_DEFAULT_REGION: us-west-1
      - name: Docs
        run: |
          npm install
          make validate_docs
