name: PR Validation
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - name: Checkout to branch
        # https://github.com/actions/checkout/releases/tag/v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up Python and Dependencies
        uses: ./.github/actions/setup-python
        with:
          python_version: ${{ matrix.python-version }}
      - name: Run Tests
        run: |
          poetry run make test
        env:
          AWS_DEFAULT_REGION: us-west-1
      - name: Docs
        run: |
          npm install
          make validate_docs
