name: PR Validation
on:
  pull_request:
    types: [ready_for_review, synchronize]
    paths-ignore:
      - '**.md'
  push:
    branches: [master, dev]
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip -q --no-input install poetry
          poetry install
      - name: Linters
        run: |
          poetry run make check
      - name: Run Tests
        run: |
          poetry run make test
        env:
          AWS_DEFAULT_REGION: us-west-1
      - name: Docs
        run: |
          npm install
          make validate_openapi
